-- AlterTable
ALTER TABLE "daily_metrics" ADD COLUMN     "delay_120_to_300s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_30_to_60s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_60_to_120s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_over_300s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_under_30s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "early_rate_120" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "early_rate_30" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "late_rate_120" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "late_rate_30" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "on_time_rate_120" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "on_time_rate_30" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "hourly_metrics" ADD COLUMN     "delay_120_to_300s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_30_to_60s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_60_to_120s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_over_300s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "delay_under_30s" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "early_rate_120" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "early_rate_30" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "late_rate_120" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "late_rate_30" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "on_time_rate_120" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "on_time_rate_30" DOUBLE PRECISION NOT NULL DEFAULT 0;
